### ISSUE TITLE
To many worklogs in limbo breaks scrolling

### ISSUE THREAD

**Issue by bjorngronbaek** [hesehus/jira-time#65]
When many worklogs without issues have been created, it is no longer possible to scroll across the jira issues shown in the bottom part of the window, which prevents drag'n'drop from working. 
The limbo section should have its own scrollbar preventing it from pushing the jira issues down below the windows bottom.

![many limbos](https://user-images.githubusercontent.com/1505914/29329703-023c163a-81f7-11e7-9993-caefe61098f1.png)

**Comment by NielsRavn** [comment]
Fixed in the latest release
